version: '3.7'
services:
    mysql:
        image: mariadb
        ports: ['3306:3306']
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=API-REST
        - MYSQL_USER=symfony
        - MYSQL_PASSWORD=password
    php:
        build: docker/php
        #ports: ['9000:9000']
        volumes: ['./symfony/:/var/www/symfony:cached']
        depends_on:
            - mysql
    nginx:
        image: nginx:1.20.2-alpine
        ports:
            - "80:80"
        volumes:
            - "./symfony/:/var/www/symfony:cached"
            - "./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - mysql
    adminer:
        container_name: adminer-wsl-bootstrap
        image: adminer:4.7.7
        restart: unless-stopped
        ports:
            - "9080:8080"